{
 "title": "MyDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"node_localhost\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Cpu_usage"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_localhost\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Available disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) ",
     "legendFormat": "available disk space"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "Written"
    }
   ]
  }
 ]
}